name: todo-dnamic

services:
  nodejs:
    type: node:12.13
    port: 3000
    build:
      - yarn install

  mysql:
    type: mysql:5.7
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: todoapp

proxy:
  nodejs:
    - todo.lndo.site:3000

tooling:
  yarn:
    service: nodejs
  node:
    service: nodejs
